# Generated by Django 4.0.1 on 2022-01-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogid', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_content', models.TextField()),
                ('blog_date', models.DateField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
